version: "3.7"
services:
  clone_hero_server:
    image: cfunseth/clone-hero-server
    ports:
    - target: 14242
      published: 14242
      protocol: udp
      mode: host
    restart: unless-stopped
    environment:
      - NAME=lostreserizos
      - PASSWORD=chichotas
    